# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./"
  command = "git submodule update --init --recursive"
  [build.environment]
    GIT_LFS_ENABLED = "1"
[[headers]]
  for="/*"
  [headers.values]
  	Access-Control-Allow-Origin = "*"
  	Access-Control-Allow-Methods ="GET, OPTIONS, HEAD"
